const menu = [
  {
    id: 1,
    title: 'vegan pancakes',
    category: 'breakfast',
    price: 6.99,
    img: './images/item-1.jpeg',
    desc: `with banana flambé, peanut butter, mix berries jam, homemade granola, strawberries and mix berries `,
  },
  {
    id: 2,
    title: 'Hulk Burger',
    category: 'lunch',
    price: 12.99,
    img: './images/item-2.jpg',
    desc: `“Beyond Meat” Plant-Based Burger, vegan cheese, vegan mayonnaise, dijon, red onions, mix leaves, red pepper and tomato mix with harissa. Served with sweet potato chips. `,
  },
  {
    id: 3,
    title: 'Berries milkshake',
    category: 'shakes',
    price: 4.95,
    img: './images/item-3.jpg',
    desc: `Soy yogurt, vanilla and mix berries smoothie with strawberry, mix berries and homemade granola`,
  },
  {
    id: 4,
    title: 'Cauliflower Wings',
    category: 'lunch',
    price: 7.95,
    img: './images/item-4.jpg',
    desc: `Crispy cauliflower bites tossed in a buffalo sauce sprinkled with sesame seeds and green onions. `,
  },
  {
    id: 5,
    title: 'Super Toast',
    category: 'breakfast',
    price: 7.99,
    img: './images/item-5.jpg',
    desc: `vegan cheese, mixed leaves, oregano, cherry tomato, wild mushrooms, avocado, sun dried tomato, mango & pineapple chutney, strawberry and chives `,
  },
  {
    id: 6,
    title: 'Açaí Bowl',
    category: 'breakfast',
    price: 10.99,
    img: './images/item-6.jpg',
    desc: `Açaí blended with banana and vanilla vegan ice cream with banana, strawberry, passion fruit, kiwi, toasted almonds, grated coconut and chia seeds`,
  },
  {
    id: 7,
    title: 'Green Bagel',
    category: 'breakfast',
    price: 8.99,
    img: './images/vegan-bagel.jpg',
    desc: `beetroot hummus, wild mushrooms, red pepper and tomato mix with harissa, caramelized onion, chives and mix leaves `,
  },
  {
    id: 8,
    title: 'Tapioca',
    category: 'lunch',
    price: 11.99,
    img: './images/item-8.jpeg',
    desc: `avocado, sun-dried tomato, oregano, wild mushrooms, red pepper and tomato mix with harissa, vegan cheese and mix leaves`,
  },
  {
    id: 9,
    title: 'quarantine buddy',
    category: 'shakes',
    price: 5.95,
    img: './images/item-9.jpeg',
    desc: `Greek vegan yogurt, banana, hazelnuts and cocoa smoothie with banana, homemade granola , coconut and strawberry`,
  },
];
export default menu;
